- docs/_config.yml
- docs/_toc.yml
- docs/home.md
- docs/workshop-1/genome.ipynb
- docs/workshop-1/malariagen-data.ipynb
After discussion we decided to swap modules 2 and 3 as the content flowed more naturally.
Also I have tentatively change the course title following Luc's suggestion.
> Reorder modules 2 and 3; change course title

- docs/workshop-1/module-1-colab.ipynb
In this PR:
* Pull all practical exercises to a dedicated section at the end of the notebook, and add a few more for good measure.
* Add the English lecture embedded.
> Add exercises and video to module 3

- docs/workshop-1/about.ipynb
- docs/workshop-1/module-1-colab.ipynb
- docs/workshop-1/module-2-sample-metadata.ipynb
- docs/workshop-1/module-4-vgsc-snps.ipynb
This PR manually merges content from #28, #27, #26.
> Add French exercises

- docs/workshop-2/about.ipynb
- docs/workshop-2/module-1-pandas.ipynb
* Standardise exericse formatting
* Add workshop 2 about
> Edits 2022-03-18

- docs/_toc.yml
- docs/home.md
- docs/workshop-2/about.ipynb
- docs/workshop-3/about.ipynb
- docs/workshop-3/module-1-plotly.ipynb
- docs/workshop-3/module-2-population-structure.ipynb
- docs/workshop-3/module-3-snps.ipynb
- docs/workshop-3/module-4-pca.ipynb
- requirements-deploy.txt
This PR sets up the table of contents for workshop 3.
> Setup workshop 3

- .github/workflows/check-book.yml
- .github/workflows/gh-pages.yml
- docs/_config.yml
- docs/_toc.yml
- docs/home.md
- docs/workshop-1/about.ipynb
- docs/workshop-2/about.ipynb
- docs/workshop-4/about.ipynb
- docs/workshop-4/module-1-numpy.ipynb
- docs/workshop-4/module-2-cryptic-species.ipynb
- requirements-deploy.txt
- requirements.txt
PR bringing in notebooks for workshop 4.
Will add in French videos and exercise translations via a subsequent PR.
> Workshop 4 content

- docs/_config.yml
> Fix math labels in plotly

- README.md
- docs/_config.yml
Add instructions on how to run local HTTP server to preview book.
> Update README with info on how to preview built book via HTTP server

- docs/workshop-8/module-1-planning-analysis.ipynb
- docs/workshop-8/module-2-presenting-results.ipynb
- docs/workshop-8/module-3-genomic-surveillance-tanzania.ipynb
- docs/workshop-8/module-4-genomic-surveillance-ghana.ipynb
Updated the video paths and the french sections on the exercises. 
Also, re-run with python 3.7 for compatibility.
> W8 - add french sections

- .github/workflows/check-book.yml
- .github/workflows/gh-pages.yml
- docs/_config.yml
- docs/workshop-8/module-3-genomic-surveillance-tanzania.ipynb
- docs/workshop-8/module-4-genomic-surveillance-ghana.ipynb
- requirements.txt
* Upgrade requirements and actions
* Suppress mime type warnings
* Fix heading level warnings
> Maintenance 2023-05-24

- .github/workflows/check-book.yml
* Resolves #143 
* Resolves #75
> W3M1 maintenance 2023-05-25

- docs/workshop-1/module-1-colab.ipynb
- docs/workshop-1/module-3-genome.ipynb
- docs/workshop-2/module-1-pandas.ipynb
- docs/workshop-2/module-3-cnv-calling.ipynb
Update to use `!pip install -qqq malariagen_data`.
* partially addresses #142
> malariagen-data install ignore bokeh error

- docs/workshop-2/module-1-pandas.ipynb
> Moves W2M1 and W2M4 diagrams to gcs with links

- docs/workshop-1/module-1-colab.ipynb
- docs/workshop-1/module-3-genome.ipynb
> W1 - add disclaimer

- docs/workshop-8/module-1-planning-analysis.ipynb
- docs/workshop-8/module-2-presenting-results.ipynb
- docs/workshop-8/module-3-genomic-surveillance-tanzania.ipynb
- docs/workshop-8/module-4-genomic-surveillance-ghana.ipynb
> W8 - maintenance

- docs/workshop-2/module-1-pandas.ipynb
> Use geneset() instead of genome_features()

- docs/workshop-7/module-1-op-ir.ipynb
Addresses #193 for this module.
Addresses #199 for this module.
Addresses #224 for this module.
Resolves #226 (it was a subclass of #199). 
Resolves #227.
> W7M1 - Updates and Maintenance 01/05/24

- docs/workshop-6/module-4-primers.ipynb
I had not translated the new HINT in the exercises into French!
> W6M4 - Updates and Maintenance 28/05/24

- docs/workshop-2/module-3-cnv-calling.ipynb
Addresses #224 for this notebook.
> W2M3 - Updates and Maintenance 24/05/24

- docs/workshop-2/module-1-pandas.ipynb
Addresses #224 for this module.
Addresses #233 for this module.
Addresses (and kind of reverses) #204 for this module.
> W2M1 - Updates and Maintenance 10/05/24

- docs/workshop-5/module-1-xarray.ipynb
> W5M1 - Updates and Maintenance 21/05/24

- docs/workshop-2/module-3-cnv-calling.ipynb
I found a few typos in the French exercises. Because only text was modified, I have not rerun the notebook on Bespin (but I checked that the code was fine on Colab).
> W2M3 - Updates and maintenance - 19/03/2025

- docs/workshop-2/module-3-cnv-calling.ipynb
> W2M4 - Updates and maintenance - 19/03/2025

- docs/general/data-access.ipynb
Added a step about granting access to Colab and a link to @ahernank's video.
> Data Access update

- docs/workshop-2/module-1-pandas.ipynb
- docs/workshop-2/module-2-metabolic-ir.ipynb
Partially addresses #297. There is an issue with module 3: #301.
> W2M1, 2 & 4 - Updates and maintenance - 26/03/2025

- docs/workshop-4/module-1-numpy.ipynb
- docs/workshop-4/module-2-cryptic-species.ipynb
Addresses #308.
Some images (from the numpy official website) have disappeared. I screenshot part of another one that contains roughly the same thing (as it seemed cleaner than taking it from one of the videos) and put it on S3.
> W4M1-4 - Maintenance - 21/04/2025

- docs/workshop-2/module-1-pandas.ipynb
- docs/workshop-2/module-4-cnv-frequencies.ipynb
- docs/workshop-3/module-4-NJT.ipynb
- docs/workshop-4/module-1-numpy.ipynb
- docs/workshop-4/module-4-taxon-analysis.ipynb
- docs/workshop-5/module-1-xarray.ipynb
- docs/workshop-5/module-4-roh.ipynb
- docs/workshop-7/module-1-op-ir.ipynb
Used addresses instead of relative paths this time. Should work better!
> Copy & update images paths to point to local repository - better this time

- docs/_toc.yml
> Add WIP modules for Af training - Part 1
